select * from finances_user;

CREATE TABLE finances_user (
  USER_ID number(19) NOT NULL,
  FIRST_NAME varchar2(45) NOT NULL,
  LAST_NAME varchar2(45) NOT NULL,
  BIRTH_DATE date NOT NULL,
  EMAIL_ADDRESS varchar2(100) NOT NULL,
  LAST_UPDATED_BY varchar2(45) NOT NULL,
  LAST_UPDATED_DATE timestamp(0) NOT NULL,
  CREATED_BY varchar2(45) NOT NULL,
  CREATED_DATE timestamp(0) NOT NULL,
  USER_ADDRESS_LINE_1 varchar2(100) DEFAULT NULL,
  USER_ADDRESS_LINE_2 varchar2(100) DEFAULT NULL,
  CITY varchar2(100) DEFAULT NULL,
  STATE varchar2(2) DEFAULT NULL,
  ZIP_CODE varchar2(5) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE SEQUENCE finances_user_seq START WITH 1 INCREMENT BY 1;


select * from credential;

CREATE TABLE credential (
  CREDENTIAL_ID number(19) NOT NULL,
  USER_ID number(19) NOT NULL,
  USERNAME varchar2(50) NOT NULL,
  PASSWORD varchar2(100) NOT NULL,
  PRIMARY KEY (CREDENTIAL_ID),
  CONSTRAINT USER_ID_UNIQUE UNIQUE  (USER_ID),
  CONSTRAINT FINANCES_USER_FK FOREIGN KEY (USER_ID) REFERENCES finances_user (USER_ID)
);


CREATE SEQUENCE credential_seq START WITH 1 INCREMENT BY 1;

select * from account;

CREATE TABLE account (
  ACCOUNT_ID number(19) NOT NULL,
  BANK_ID number(19) DEFAULT NULL,
  ACCOUNT_TYPE varchar2(45) DEFAULT NULL,
  NAME varchar2(100) DEFAULT NULL,
  INITIAL_BALANCE number(10,2) NOT NULL,
  CURRENT_BALANCE number(10,2) NOT NULL,
  OPEN_DATE date NOT NULL,
  CLOSE_DATE date NOT NULL,
  LAST_UPDATED_BY varchar2(45) NOT NULL,
  LAST_UPDATED_DATE timestamp(0) DEFAULT NULL,
  CREATED_BY varchar2(45) DEFAULT NULL,
  CREATED_DATE timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ACCOUNT_ID)
);

CREATE SEQUENCE account_seq START WITH 2 INCREMENT BY 1;

select * from transaction;

CREATE TABLE transaction (
  TRANSACTION_ID number(19) NOT NULL,
  ACCOUNT_ID number(19) NOT NULL,
  TRANSACTION_TYPE varchar2(45) NOT NULL,
  TITLE varchar2(100) NOT NULL,
  AMOUNT number(10,2) NOT NULL,
  INITIAL_BALANCE number(10,2) NOT NULL,
  CLOSING_BALANCE number(10,2) NOT NULL,
  NOTES clob,
  LAST_UPDATED_BY varchar2(45) NOT NULL,
  LAST_UPDATED_DATE timestamp(0) NOT NULL,
  CREATED_BY varchar2(45) NOT NULL,
  CREATED_DATE timestamp(0) NOT NULL,
  PRIMARY KEY (TRANSACTION_ID),
  CONSTRAINT ACCOUNT_FK2 FOREIGN KEY (ACCOUNT_ID) REFERENCES account (ACCOUNT_ID)
);

CREATE SEQUENCE transaction_seq START WITH 13 INCREMENT BY 1;

select * from budget;

CREATE TABLE budget (
  BUDGET_ID number(19) NOT NULL,
  NAME varchar2(100) NOT NULL,
  GOAL_AMOUNT number(10,2) NOT NULL,
  PERIOD varchar2(45) NOT NULL,
  PRIMARY KEY (BUDGET_ID)
);

CREATE SEQUENCE budget_seq START WITH 20 INCREMENT BY 1;

select * from budget_transaction;

CREATE TABLE budget_transaction (
  TRANSACTION_ID number(19) NOT NULL,
  BUDGET_ID number(19) NOT NULL,
  PRIMARY KEY (TRANSACTION_ID,BUDGET_ID),
  CONSTRAINT TRANSACTION_ID_UNIQUE UNIQUE  (TRANSACTION_ID),
  CONSTRAINT BUDGET_FK FOREIGN KEY (BUDGET_ID) REFERENCES budget (BUDGET_ID),
  CONSTRAINT TRANSACTION_FK2 FOREIGN KEY (TRANSACTION_ID) REFERENCES transaction (TRANSACTION_ID)
);


select * from user_account;

CREATE TABLE user_account (
  USER_ID number(19) NOT NULL,
  ACCOUNT_ID number(19) NOT NULL,
  PRIMARY KEY (USER_ID,ACCOUNT_ID),
  CONSTRAINT ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES account (ACCOUNT_ID),
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES finances_user (USER_ID)
);

